name: run-tests

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix develop --command bash -c 'nixunits build TOTO -cc "{ services.httpd.enable = true; }" -6'
