name: run-tests

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run moi ça…
      uses: addnab/docker-run-action@v3
      with:
        image: nixos/nix
        options: --privileged -v ${{ github.workspace }}:/workspace
        run: |
          cd /workspace
          ls
          nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command bash -c 'nixunits build TOTO -cc "{ services.httpd.enable = true; }" -6'
