name: run-tests

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: nixos/nix
    steps:
    - uses: actions/checkout@v4
    - run: |
        nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command bash -c 'nixunits build TOTO -cc "{ services.httpd.enable = true; }" -6'
